# <!-- Powered by BMAD™ Core -->
# Nano Banana Hackathon Configuration
project:
  name: "Nano Banana Hackathon"
  description: "Consumer app using Gemini 2.5 Flash Image"
  hackathon: true
  deadline: "September 6, 2025"
  
markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: 
  - docs/HACKATHON_RESOURCES.md
  - docs/API_KEYS_SETUP.md
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
  - HACKATHON_RESOURCES.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad

# Hackathon specific config
hackathonContext:
  mainAPI: "Gemini 2.5 Flash Image"
  partners: ["ElevenLabs", "Fal AI"]
  judges: "Google DeepMind"
  focus: "Consumer applications"
